#!/bin/bash

################################################################################
# REE AI Platform - Backup Setup Helper Script
################################################################################
#
# DESCRIPTION:
#   Interactive setup script to create backup configuration and test backups.
#   Walks through configuration options and validates the setup.
#
# USAGE:
#   ./backup-setup.sh
#
# FEATURES:
#   - Interactive configuration wizard
#   - Configuration validation
#   - Backup testing
#   - Cron job setup (Linux)
#
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
NC='\033[0m'

echo -e "${BLUE}=================================="
echo "REE AI Platform - Backup Setup"
echo "==================================${NC}"
echo ""

# Check if .backup.env exists
if [[ -f "$SCRIPT_DIR/.backup.env" ]]; then
    echo -e "${YELLOW}Warning: .backup.env already exists${NC}"
    read -p "Do you want to reconfigure? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Using existing configuration"
        exit 0
    fi
fi

# Interactive configuration
echo -e "${BLUE}PostgreSQL Configuration${NC}"
read -p "PostgreSQL Host [localhost]: " pg_host
pg_host=${pg_host:-localhost}

read -p "PostgreSQL Port [5432]: " pg_port
pg_port=${pg_port:-5432}

read -p "PostgreSQL Database [ree_ai]: " pg_db
pg_db=${pg_db:-ree_ai}

read -p "PostgreSQL User [ree_ai_user]: " pg_user
pg_user=${pg_user:-ree_ai_user}

read -sp "PostgreSQL Password: " pg_password
echo
if [[ -z "$pg_password" ]]; then
    echo -e "${RED}Error: Password is required${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Backup Configuration${NC}"
read -p "Backup Directory [./backups]: " backup_dir
backup_dir=${backup_dir:-./backups}

read -p "Retention Days [30]: " retention_days
retention_days=${retention_days:-30}

echo ""
read -p "Enable OpenSearch backup? (y/n) [y]: " -n 1 -r
echo
opensearch_enabled=${REPLY:-y}
if [[ $opensearch_enabled =~ ^[Yy]$ ]]; then
    opensearch_enabled="true"
    read -p "OpenSearch Host [localhost]: " os_host
    os_host=${os_host:-localhost}
else
    opensearch_enabled="false"
    os_host="localhost"
fi

echo ""
read -p "Enable S3 upload? (y/n) [n]: " -n 1 -r
echo
s3_enabled=${REPLY:-n}
if [[ $s3_enabled =~ ^[Yy]$ ]]; then
    s3_enabled="true"
    read -p "S3 Bucket: " s3_bucket
    read -p "S3 Region [us-east-1]: " s3_region
    s3_region=${s3_region:-us-east-1}
    read -p "AWS Access Key ID: " aws_key_id
    read -sp "AWS Secret Access Key: " aws_secret_key
    echo
else
    s3_enabled="false"
    s3_bucket=""
    s3_region="us-east-1"
    aws_key_id=""
    aws_secret_key=""
fi

echo ""
read -p "Enable email notifications? (y/n) [n]: " -n 1 -r
echo
email_enabled=${REPLY:-n}
if [[ $email_enabled =~ ^[Yy]$ ]]; then
    email_enabled="true"
    read -p "Email Recipient: " email_recipient
    read -p "SMTP Server: " smtp_server
    read -p "SMTP Port [587]: " smtp_port
    smtp_port=${smtp_port:-587}
    read -p "SMTP User: " smtp_user
    read -sp "SMTP Password: " smtp_password
    echo
else
    email_enabled="false"
    email_recipient=""
    smtp_server=""
    smtp_port="587"
    smtp_user=""
    smtp_password=""
fi

# Create configuration file
echo ""
echo -e "${BLUE}Creating configuration file...${NC}"

cat > "$SCRIPT_DIR/.backup.env" << EOF
# REE AI Platform - Backup Configuration
# Generated by backup-setup.sh on $(date)

# Backup Location
BACKUP_DIR=$backup_dir

# PostgreSQL Configuration
POSTGRES_HOST=$pg_host
POSTGRES_PORT=$pg_port
POSTGRES_DB=$pg_db
POSTGRES_USER=$pg_user
POSTGRES_PASSWORD=$pg_password

# OpenSearch Configuration
OPENSEARCH_ENABLED=$opensearch_enabled
OPENSEARCH_HOST=$os_host
OPENSEARCH_PORT=9200

# S3 Configuration
S3_ENABLED=$s3_enabled
S3_BUCKET=$s3_bucket
S3_REGION=$s3_region
S3_PREFIX=ree-ai-backups
AWS_ACCESS_KEY_ID=$aws_key_id
AWS_SECRET_ACCESS_KEY=$aws_secret_key

# Backup Retention
RETENTION_DAYS=$retention_days

# Email Notifications
ENABLE_EMAIL=$email_enabled
EMAIL_RECIPIENT=$email_recipient
SMTP_SERVER=$smtp_server
SMTP_PORT=$smtp_port
SMTP_USER=$smtp_user
SMTP_PASSWORD=$smtp_password

# Logging
LOG_FILE=$SCRIPT_DIR/backup.log

# Other Settings
DRY_RUN=false
DROP_DB_BEFORE_RESTORE=false
EOF

chmod 600 "$SCRIPT_DIR/.backup.env"
echo -e "${GREEN}Configuration file created: $SCRIPT_DIR/.backup.env${NC}"

# Test configuration
echo ""
echo -e "${BLUE}Testing configuration...${NC}"

# Source the config
source "$SCRIPT_DIR/.backup.env"

# Check prerequisites
echo "Checking prerequisites..."
missing_tools=()

for tool in tar gzip curl psql; do
    if ! command -v "$tool" &> /dev/null; then
        missing_tools+=("$tool")
    fi
done

if [[ ${#missing_tools[@]} -gt 0 ]]; then
    echo -e "${YELLOW}Warning: Missing tools: ${missing_tools[*]}${NC}"
    echo "Please install these tools before running backups"
else
    echo -e "${GREEN}All prerequisites found${NC}"
fi

# Test PostgreSQL connection
echo "Testing PostgreSQL connection..."
if PGPASSWORD="$POSTGRES_PASSWORD" psql \
    -h "$POSTGRES_HOST" \
    -p "$POSTGRES_PORT" \
    -U "$POSTGRES_USER" \
    -d "$POSTGRES_DB" \
    -c "SELECT version();" &> /dev/null; then
    echo -e "${GREEN}PostgreSQL connection successful${NC}"
else
    echo -e "${RED}Failed to connect to PostgreSQL${NC}"
    echo "Please verify connection parameters"
fi

# Test OpenSearch connection if enabled
if [[ "$OPENSEARCH_ENABLED" == "true" ]]; then
    echo "Testing OpenSearch connection..."
    if curl -s "http://$OPENSEARCH_HOST:$OPENSEARCH_PORT/" > /dev/null 2>&1; then
        echo -e "${GREEN}OpenSearch connection successful${NC}"
    else
        echo -e "${YELLOW}Warning: Could not connect to OpenSearch${NC}"
    fi
fi

echo ""
echo -e "${BLUE}Setup Summary${NC}"
echo "=============="
echo "PostgreSQL Host: $POSTGRES_HOST:$POSTGRES_PORT"
echo "Database: $POSTGRES_DB"
echo "Backup Directory: $backup_dir"
echo "Retention: $retention_days days"
echo "OpenSearch: $opensearch_enabled"
echo "S3 Upload: $s3_enabled"
echo "Email Notifications: $email_enabled"
echo ""

# Option to setup cron job
if [[ "$OSTYPE" != "msys" ]] && [[ "$OSTYPE" != "cygwin" ]]; then
    echo ""
    read -p "Setup daily backup cron job? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Enter the time for daily backup (HH:MM) [02:00]: "
        read -p "> " backup_time
        backup_time=${backup_time:-02:00}

        # Parse time
        hour=$(echo $backup_time | cut -d: -f1)
        minute=$(echo $backup_time | cut -d: -f2)

        # Create cron entry
        cron_entry="$minute $hour * * * cd $ROOT_DIR && ./scripts/backup.sh >> ./scripts/backup.log 2>&1"

        # Check if cron entry already exists
        if crontab -l 2>/dev/null | grep -q "backup.sh"; then
            echo -e "${YELLOW}Cron job for backup already exists${NC}"
        else
            # Add cron job
            (crontab -l 2>/dev/null; echo "$cron_entry") | crontab -
            echo -e "${GREEN}Cron job created: $backup_time daily${NC}"
            echo "To view: crontab -l"
            echo "To remove: crontab -r"
        fi
    fi
fi

echo ""
echo -e "${GREEN}Setup completed!${NC}"
echo ""
echo "Next steps:"
echo "1. Test backup: cd $ROOT_DIR && ./scripts/backup.sh --dry-run"
echo "2. Run backup: cd $ROOT_DIR && ./scripts/backup.sh"
echo "3. List backups: cd $ROOT_DIR && ./scripts/restore.sh list"
echo "4. Restore: cd $ROOT_DIR && ./scripts/restore.sh restore latest"
echo ""
echo "For more information, see: $SCRIPT_DIR/BACKUP_README.md"
